{"name": "Создание пользователя который уже есть в системе", "status": "passed", "description": "При создании дублирующего пользователя срабатывает allert ", "start": 1720115554901, "stop": 1720115555164, "uuid": "4513c3ce-1365-4aac-bf99-9e5cb4bdafa5", "historyId": "511af5c3d1ba0594e424965a597653ae", "testCaseId": "511af5c3d1ba0594e424965a597653ae", "fullName": "tests.test_create_user.TestCreateUser#test_create_double_user_error", "labels": [{"name": "suite", "value": "Создание пользователя"}, {"name": "parentSuite", "value": "tests"}, {"name": "subSuite", "value": "TestCreateUser"}, {"name": "host", "value": "DESKTOP-9BVNBF5"}, {"name": "thread", "value": "8120-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_user"}]}