{"name": "Авторизация под пользователем, который есть в системе", "status": "passed", "description": "При авторизация под пользователем, который есть в системе, происходит успешная авторизация", "start": 1720115561809, "stop": 1720115562464, "uuid": "38aa2134-2820-4bd1-9cbf-ab12a4652ddc", "historyId": "c1ee95458348aabac0acb25665322199", "testCaseId": "c1ee95458348aabac0acb25665322199", "fullName": "tests.test_login_user.Testlogin#test_login_user", "labels": [{"name": "suite", "value": "Авторизация пользователя"}, {"name": "parentSuite", "value": "tests"}, {"name": "subSuite", "value": "Testlogin"}, {"name": "host", "value": "DESKTOP-9BVNBF5"}, {"name": "thread", "value": "8120-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}